### ISSUE TITLE
Add stackage nightly build to the CI

### ISSUE THREAD

**Issue by decentral1se** [qfpl/tasty-hedgehog#17]
https://github.com/lwm/tasty-discover/blob/185485536bb9ac5ccb1ff7b9379717f78b4dca8b/.travis.yml#L63

Would help catch nightly build failures locally here.

Can do it later, just raising issue now.

**Comment by decentral1se** [comment]
I've taken a look at adding this and it looks pretty difficult to add it into the generated .travis.yml.

Also, I'm wondering, should anything be manually added to this script? If you will generate again ...

I basically want to get the following in:

```
matrix:
  include:
    ...
    - env: BUILD=stackage
  allow_failures:
    - env: BUILD=stackage

script:
      - stack build --resolver nightly --haddock --test --bench --no-run-benchmarks
```

Any ideas? Would be good to quickly catch Stackage failures ...
